name: 'google-chat-notification'
description: 'Google chat notification from your github action'
author: 'premagic'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'bell'
  color: 'green'

# Define your inputs here.
inputs:
  name:
    description: 'Name of the job'
    required: true
  url:
    description: 'Webhook url'
    required: true
  status:
    description: 'Status'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
